baseURL: "jonybepary.github.io/site_test"
title: Jonys blog
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        title: Jony's Blog
        homeInfoParams:
            Title: "Welcome \U0001F44B"
            Content: >
                Here my thought, Story and Ideas.
        socialIcons:
            - name: github
              url: "https://github.com/JonyBepary"
            - name: facebook
              url: "https://facebook.com/sa.jhone"
            - name: RsS
              url: "index.xml"

        editPost:
            URL: "https://github.com/JonyBepary/Jonys-Blog/tree/master/content"
            Text: "Suggest Changes" # edit text
            appendFilePath: true # to append file path to Edit link


        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Categories
                  url: categories/
                  weight: 10

    bn:
        languageName: "বাংলা"
        languageAltTitle: bn
        weight: 2
        title: জনির ব্লগ

        homeInfoParams:
            Title: "স্বাগত \U0001F44B"
            Content: >
                মোর আগ্রহের আর্কাইভ
        socialIcons:
            - name: github
              url: "https://github.com/JonyBepary"
            - name: facebook
              url: "https://facebook.com/sa.jhone"
            - name: RsS
              url: "index.xml"

        editPost:
            URL: "https://github.com/JonyBepary/Jonys-Blog/tree/master/content"
            Text: "Suggest Changes" # edit text
            appendFilePath: true # to append file path to Edit link


        menu:
            main:
                - name: আর্কাইভ
                  url: archives/
                  weight: 5
                - name: ট্যাগস
                  url: tags
                  weight: 10
                - name: ক্যাটাগওরি
                  url: categories
                  weight: 10
                - name: সিরিজ
                  url: series
                  weight: 10
                - name: সার্চ
                  url: search/
                  weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Welcome to My Blog.
Here you'll find some of those things that intrigued me. Maybe it's pretty simple or very complex sometimes can be complicated.But If it fascinates me. You'll find it here. It's all about me.
Mostly you can expect things like Data Structure, Algorithm Analysis, Math, and many more."
    author: Jony Bepary
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    TocOpen: false

    # comments: false
    images: ["Cover.png"]

    # profileMode:
    #     enabled: false
    #     title: PaperMod
    #     imageUrl: "#"
    #     imageTitle: my image
    #     # imageWidth: 120
    #     # imageHeight: 120
    #     buttons:
    #         - name: Archives
    #           url: archives
    #         - name: Tags
    #           url: tags

    # homeInfoParams:
    #     Title: "Jony's blog"
    #     Content: >
    #             Welcome to My Blog. Here you'll find some of those Things that intruged me.
    #             Maybe it's pretty simple or very complex sometimes it can be complicated.
    #             But If it's fasinates me. You'll find here. It's all about me.
    #             Mostly you can expect things like Data Structure, Algorithm Analysis, Math and many more.
    # socialIcons:
    #     - name: github
    #       url: "https://github.com/JonyBepary"
    #     - name: facebook
    #       url: "https://facebook.com/sa.jhone"
    #     - name: RsS
    #       url: "index.xml"

    # editPost:
    #     URL: "URL: "https://github.com/JonyBepary/Jonys-Blog/tree/master/content"
    #     Text: "Suggest Changes" # edit text
    #     appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

            # SiteVerificationTag: "XYZabc"

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]
params:
    assets:
        disableFingerprinting: false
    analytics:
        google:
            GTMCode: GTM-NC8JWD9

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
